# Generated by Django 2.2.4 on 2019-08-18 01:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Nome completo do seu Abrigo/ONG')),
                ('subTitulo', models.CharField(max_length=255, null=True, verbose_name='Sigla do seu Abrigo/ONG')),
                ('texto', models.CharField(max_length=50, verbose_name='Telefone (XX)XXXX-XXXX')),
                ('ativo', models.BooleanField(default=False)),
                ('status', models.CharField(default=1, max_length=2)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(default=0, max_length=2)),
                ('login_senha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Redator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_abrigo_completo', models.CharField(max_length=255, null=True, verbose_name='Nome completo do seu Abrigo/ONG')),
                ('nickname', models.CharField(max_length=255, null=True, verbose_name='Sigla do seu Abrigo/ONG')),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('facebook', models.CharField(max_length=255, null=True, verbose_name='Link do Facebook')),
                ('twitter', models.CharField(max_length=255, null=True, verbose_name='Link do Twitter')),
                ('github', models.CharField(max_length=255, null=True, verbose_name='Link do GitHub')),
                ('instagram', models.CharField(max_length=255, null=True, verbose_name='Link do Instagram')),
                ('logo', models.FileField(default='fotos/anonymous.jpg', null=True, upload_to='fotos', verbose_name='Icone/Logo do seu Abrigo/ONG')),
                ('pais', models.CharField(default='BR', max_length=5, null=True, verbose_name='País, sigla (BR,EUA,CH) ')),
                ('estado', models.CharField(max_length=4, verbose_name='Estado, sigla (SP, RJ, RS)')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade do seu abrigo/ONG')),
                ('descricao', models.TextField(max_length=255, null=True, verbose_name='Breve descriçãp do seu abrigo/ONG')),
                ('telefone', models.CharField(max_length=50, verbose_name='Telefone (XX)XXXX-XXXX')),
                ('ativo', models.BooleanField(default=True)),
                ('status', models.CharField(default=1, max_length=2)),
                ('login_senha', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visualizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('gerente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='home.Gerente')),
                ('redator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='home.Redator')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, null=True, verbose_name='Nome completo do seu Abrigo/ONG')),
                ('subTitulo', models.CharField(max_length=255, null=True, verbose_name='Sigla do seu Abrigo/ONG')),
                ('assunto', models.CharField(max_length=255, null=True, verbose_name='Link do Facebook')),
                ('texto', models.CharField(max_length=50, verbose_name='Telefone (XX)XXXX-XXXX')),
                ('ativo', models.BooleanField(default=False)),
                ('status', models.CharField(default=1, max_length=2)),
                ('data_criacao', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('artigo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='artigo', to='home.Artigo')),
                ('leitor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redator', to='home.Redator')),
            ],
        ),
        migrations.AddField(
            model_name='artigo',
            name='redator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='escritor', to='home.Redator'),
        ),
    ]
