# Generated by Django 2.2.4 on 2019-08-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190818_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='assunto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='subTitulo',
        ),
    ]
