# Generated by Django 2.2.4 on 2019-08-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190818_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redator',
            name='nickname',
        ),
    ]
