# Generated by Django 2.2.4 on 2019-08-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_redator_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(max_length=50, verbose_name='Telefone (XX)XXXX-XXXX'),
        ),
    ]
