# Generated by Django 2.2.4 on 2019-08-18 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_comentario_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='subTitulo',
            new_name='tema',
        ),
    ]
