# Generated by Django 2.2.4 on 2019-08-18 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190818_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigo',
            old_name='subTitulo',
            new_name='tema',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='titulo',
        ),
    ]
