# Generated by Django 2.2.4 on 2019-08-18 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190818_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizacao',
            name='gerente',
        ),
        migrations.RemoveField(
            model_name='visualizacao',
            name='redator',
        ),
        migrations.AddField(
            model_name='visualizacao',
            name='artigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='home.Comentario'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(max_length=50, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=50, verbose_name='Comentario'),
        ),
    ]
