# Generated by Django 2.2.4 on 2019-08-18 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190818_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizacao',
            name='artigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viss_artigo', to='home.Artigo'),
        ),
    ]
