# Generated by Django 2.2.4 on 2019-08-18 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20190818_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='redator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escritor', to='home.Redator'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artigo', to='home.Artigo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='leitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redator', to='home.Redator'),
        ),
    ]
