# Generated by Django 2.2.4 on 2019-08-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190818_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='tema',
            field=models.CharField(max_length=255, null=True, verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(max_length=50, verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='titulo',
            field=models.CharField(max_length=255, null=True, verbose_name='Título'),
        ),
    ]
