# Generated by Django 2.2.4 on 2019-08-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190818_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, null=True, verbose_name='Tema')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='tema',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Artigo'),
        ),
        migrations.AlterField(
            model_name='redator',
            name='nome_completo',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome completo'),
        ),
    ]
