# Generated by Django 2.2.4 on 2019-08-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20190823_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='tema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.Tema'),
            preserve_default=False,
        ),
    ]
