# Generated by Django 2.2.4 on 2019-08-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20190823_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='texto',
            field=models.TextField(verbose_name='Matéria'),
        ),
        migrations.AlterField(
            model_name='redator',
            name='cidade',
            field=models.CharField(max_length=80, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='redator',
            name='descricao',
            field=models.TextField(max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='redator',
            name='estado',
            field=models.CharField(max_length=4, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='redator',
            name='logo',
            field=models.FileField(default='fotos/anonymous.jpg', null=True, upload_to='fotos', verbose_name='Foto Perfil'),
        ),
    ]
