# Generated by Django 2.2.4 on 2019-08-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190828_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='lido',
            field=models.BooleanField(default=False),
        ),
    ]
