# Generated by Django 2.2.4 on 2019-08-29 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_contato_lido'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='data',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
